CREATE TABLE metas (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome               TEXT NOT NULL,
    valor_alvo         NUMERIC(19,2) NOT NULL,
    valor_atual        NUMERIC(19,2) NOT NULL DEFAULT 0,
    prazo              TEXT,
    cor                TEXT NOT NULL DEFAULT '#6366f1',
    icone              TEXT NOT NULL DEFAULT 'target',
    data_cancelamento  TEXT,
    criado_em          TEXT NOT NULL,
    espaco_id          BIGINT NOT NULL REFERENCES espacos(id),
    usuario_id         BIGINT NOT NULL REFERENCES usuarios(id)
);

CREATE INDEX idx_metas_espaco ON metas(espaco_id);

-- Aporte/resgate de meta vira uma Transacao real (débito/crédito numa
-- conta) — meta_id só marca a origem, pra permitir listar o histórico de
-- movimentações de uma meta reaproveitando a tabela de transações.
ALTER TABLE transacoes ADD COLUMN meta_id BIGINT REFERENCES metas(id);
CREATE INDEX idx_transacoes_meta ON transacoes(meta_id);
