-- Dívida é só um "rótulo" sobre um grupo de parcelas (Transacao já suporta
-- parcelamento via grupo_parcela_id) — nenhuma coluna nova em transacoes.
CREATE TABLE dividas (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao         TEXT NOT NULL,
    credor            TEXT,
    valor_total       NUMERIC(19,2) NOT NULL,
    total_parcelas    INTEGER NOT NULL,
    conta_id          BIGINT NOT NULL REFERENCES contas(id),
    categoria_id      BIGINT REFERENCES categorias(id),
    grupo_parcela_id  TEXT NOT NULL,
    data_inicio       TEXT NOT NULL,
    data_cancelamento TEXT,
    criado_em         TEXT NOT NULL,
    espaco_id         BIGINT NOT NULL REFERENCES espacos(id),
    usuario_id        BIGINT NOT NULL REFERENCES usuarios(id)
);

CREATE INDEX idx_dividas_espaco ON dividas(espaco_id);
CREATE INDEX idx_dividas_grupo_parcela ON dividas(grupo_parcela_id);

-- Cresce muito com transferências, parcelamentos, faturas e agora dívidas
-- todos usando grupo_parcela_id/transferencia_id — sem índice vira scan.
CREATE INDEX idx_transacoes_grupo_parcela ON transacoes(grupo_parcela_id);
