CREATE TABLE ativos (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome               TEXT NOT NULL,
    tipo               TEXT NOT NULL,
    conta_id           BIGINT NOT NULL REFERENCES contas(id),
    valor_atual        NUMERIC(19,2) NOT NULL DEFAULT 0,
    cor                TEXT NOT NULL DEFAULT '#6366f1',
    icone              TEXT NOT NULL DEFAULT 'trending-up',
    data_cancelamento  TEXT,
    criado_em          TEXT NOT NULL,
    espaco_id          BIGINT NOT NULL REFERENCES espacos(id),
    usuario_id         BIGINT NOT NULL REFERENCES usuarios(id)
);

CREATE INDEX idx_ativos_espaco ON ativos(espaco_id);

CREATE TABLE movimentacoes_ativo (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ativo_id      BIGINT NOT NULL REFERENCES ativos(id),
    tipo          TEXT NOT NULL,
    valor         NUMERIC(19,2) NOT NULL,
    data          TEXT NOT NULL,
    transacao_id  BIGINT REFERENCES transacoes(id),
    espaco_id     BIGINT NOT NULL REFERENCES espacos(id)
);

CREATE INDEX idx_movimentacoes_ativo_espaco ON movimentacoes_ativo(espaco_id);
CREATE INDEX idx_movimentacoes_ativo_ativo ON movimentacoes_ativo(ativo_id, data);
