-- Rendimento automático de investimentos: cada ativo passa a poder ter um
-- indexador (CDI/Selic/IPCA+/pré-fixado) que credita rendimento sozinho, uma
-- vez por mês, via AgendadorRendimento. `rendido_ate` é a chave da
-- idempotência (último mês já processado); sem indexador (NENHUMA, default)
-- o ativo continua 100% manual como hoje.

ALTER TABLE ativos ADD COLUMN remuneracao_tipo TEXT NOT NULL DEFAULT 'NENHUMA';
ALTER TABLE ativos ADD COLUMN taxa NUMERIC(9,4);
ALTER TABLE ativos ADD COLUMN rendido_ate TEXT;
ALTER TABLE ativos ADD COLUMN inicio_rendimento TEXT;
ALTER TABLE ativos ADD COLUMN isento_ir BOOLEAN NOT NULL DEFAULT false;

-- Cache local das séries mensais do SGS/Banco Central (CDI, Selic, IPCA).
-- Dado público, sem espaco_id — mesma natureza do catálogo de bancos (V7).
CREATE TABLE indices_economicos (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo   TEXT NOT NULL,
    mes      TEXT NOT NULL,
    valor    NUMERIC(12,8) NOT NULL,
    UNIQUE (codigo, mes)
);
