-- Baseline consolidado do schema para PostgreSQL. Substitui as migrations
-- SQLite (V1–V6) do modo desktop-local, que foi descontinuado — o Postgres
-- sobe vazio e este arquivo já representa o estado final: espaços (tenant),
-- usuários, vínculo N:N e as tabelas de dados (contas, categorias,
-- transações), todas com espaco_id e FKs reais.
--
-- Sem seed de categorias: categorias padrão são semeadas em código por
-- SemeadorCategoriasPadrao a cada novo espaço registrado.

CREATE TABLE espacos (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome      TEXT NOT NULL,
    tipo      TEXT NOT NULL DEFAULT 'PESSOAL',   -- PESSOAL | EMPRESA
    plano     TEXT NOT NULL DEFAULT 'GRATUITO',  -- GRATUITO | PAGO
    criado_em TEXT NOT NULL
);

CREATE TABLE usuarios (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email                TEXT NOT NULL UNIQUE,
    senha_hash           TEXT,
    nome                 TEXT NOT NULL,
    precisa_trocar_senha BOOLEAN NOT NULL DEFAULT false,
    criado_em            TEXT NOT NULL
);

CREATE TABLE usuarios_espacos (
    usuario_id BIGINT NOT NULL REFERENCES usuarios(id),
    espaco_id  BIGINT NOT NULL REFERENCES espacos(id),
    papel      TEXT NOT NULL DEFAULT 'DONO',     -- DONO | MEMBRO
    PRIMARY KEY (usuario_id, espaco_id)
);

CREATE TABLE contas (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome      TEXT NOT NULL,
    tipo      TEXT NOT NULL DEFAULT 'CORRENTE',
    saldo     NUMERIC(19,2) NOT NULL DEFAULT 0,
    cor       TEXT NOT NULL DEFAULT '#6366f1',
    icone     TEXT NOT NULL DEFAULT 'wallet',
    espaco_id BIGINT NOT NULL REFERENCES espacos(id)
);

CREATE TABLE categorias (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome      TEXT NOT NULL,
    tipo      TEXT NOT NULL,
    cor       TEXT NOT NULL DEFAULT '#6366f1',
    icone     TEXT NOT NULL DEFAULT 'tag',
    espaco_id BIGINT NOT NULL REFERENCES espacos(id)
);

CREATE TABLE transacoes (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conta_id           BIGINT NOT NULL REFERENCES contas(id),
    categoria_id       BIGINT REFERENCES categorias(id),
    tipo               TEXT NOT NULL,
    tipo_pagamento     TEXT NOT NULL DEFAULT 'DEBITO',
    valor              NUMERIC(19,2) NOT NULL,
    descricao          TEXT,
    data               TEXT NOT NULL,
    fixa               BOOLEAN NOT NULL DEFAULT false,
    saldo_ajustado     BOOLEAN NOT NULL DEFAULT true,
    total_parcelas     INTEGER,
    numero_parcela     INTEGER,
    grupo_parcela_id   TEXT,
    criado_em          TEXT NOT NULL,
    espaco_id          BIGINT NOT NULL REFERENCES espacos(id),
    usuario_id         BIGINT NOT NULL REFERENCES usuarios(id)
);

CREATE INDEX idx_contas_espaco     ON contas(espaco_id);
CREATE INDEX idx_categorias_espaco ON categorias(espaco_id);
CREATE INDEX idx_transacoes_espaco ON transacoes(espaco_id);
CREATE INDEX idx_transacoes_usuario ON transacoes(usuario_id);
