INSERT INTO categories (name, type, color, icon) VALUES
('Alimentação',     'EXPENSE', '#ef4444', 'utensils'),
('Supermercado',    'EXPENSE', '#f97316', 'shopping-cart'),
('Transporte',      'EXPENSE', '#eab308', 'car'),
('Saúde',           'EXPENSE', '#22c55e', 'heart-pulse'),
('Moradia',         'EXPENSE', '#3b82f6', 'home'),
('Lazer',           'EXPENSE', '#a855f7', 'gamepad-2'),
('Roupas',          'EXPENSE', '#ec4899', 'shirt'),
('Educação',        'EXPENSE', '#06b6d4', 'book-open'),
('Assinaturas',     'EXPENSE', '#8b5cf6', 'tv'),
('Outros',          'EXPENSE', '#6b7280', 'ellipsis'),
('Salário',         'INCOME',  '#22c55e', 'briefcase'),
('Freelance',       'INCOME',  '#10b981', 'laptop'),
('Investimentos',   'INCOME',  '#f59e0b', 'trending-up'),
('Outros',          'INCOME',  '#6b7280', 'plus-circle');
