-- Tokens de atualização (refresh tokens) para a sessão de inatividade com
-- renovação silenciosa. Guarda só o hash SHA-256 do token opaco entregue ao
-- navegador via cookie httpOnly — o valor bruto nunca é persistido. A janela
-- desliza por substituição (não por update): cada renovação marca o token
-- atual como revogado e cria uma linha nova com expira_em = agora + TTL.
-- Reuso de um token já revogado/expirado é tratado como possível roubo e
-- derruba todos os tokens ativos do usuário.

CREATE TABLE tokens_atualizacao (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash       TEXT NOT NULL UNIQUE,
    usuario_id       BIGINT NOT NULL REFERENCES usuarios(id),
    espaco_id        BIGINT NOT NULL REFERENCES espacos(id),
    expira_em        TEXT NOT NULL,
    criado_em        TEXT NOT NULL,
    revogado         BOOLEAN NOT NULL DEFAULT false,
    revogado_em      TEXT,
    substituido_por  TEXT,
    user_agent       TEXT
);

CREATE INDEX idx_tokens_atualizacao_usuario ON tokens_atualizacao(usuario_id);
