-- Cartão de crédito e fatura. Compras no cartão (itens_fatura) nunca tocam
-- saldo de conta diretamente: no dia do fechamento, o AgendadorFatura soma os
-- itens ainda soltos (fatura_id nulo) de cada cartão, cria UMA despesa
-- (débito) na conta de pagamento do cartão e associa os itens à fatura
-- recém-criada. Essa despesa segue o mesmo ciclo de vida manual das demais
-- transações (V3): nasce pendente, e "pagar a fatura" é só marcar essa
-- despesa como paga.

CREATE TABLE cartoes (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome                TEXT NOT NULL,
    limite              NUMERIC(19,2) NOT NULL,
    dia_fechamento      INTEGER NOT NULL,
    dia_vencimento      INTEGER NOT NULL,
    conta_pagamento_id  BIGINT NOT NULL REFERENCES contas(id),
    cor                 TEXT NOT NULL DEFAULT '#6366f1',
    icone               TEXT NOT NULL DEFAULT 'credit-card',
    espaco_id           BIGINT NOT NULL REFERENCES espacos(id)
);

CREATE TABLE faturas (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cartao_id             BIGINT NOT NULL REFERENCES cartoes(id),
    data_fechamento       TEXT NOT NULL,
    data_vencimento       TEXT NOT NULL,
    transacao_despesa_id  BIGINT NOT NULL REFERENCES transacoes(id),
    espaco_id             BIGINT NOT NULL REFERENCES espacos(id)
);

CREATE TABLE itens_fatura (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cartao_id          BIGINT NOT NULL REFERENCES cartoes(id),
    categoria_id       BIGINT REFERENCES categorias(id),
    fatura_id          BIGINT REFERENCES faturas(id),
    valor              NUMERIC(19,2) NOT NULL,
    descricao          TEXT,
    data               TEXT NOT NULL,
    total_parcelas     INTEGER,
    numero_parcela     INTEGER,
    grupo_parcela_id   TEXT,
    data_cancelamento  TEXT,
    criado_em          TEXT NOT NULL,
    espaco_id          BIGINT NOT NULL REFERENCES espacos(id),
    usuario_id         BIGINT NOT NULL REFERENCES usuarios(id)
);

CREATE INDEX idx_cartoes_espaco       ON cartoes(espaco_id);
CREATE INDEX idx_faturas_espaco       ON faturas(espaco_id);
CREATE INDEX idx_faturas_cartao       ON faturas(cartao_id);
CREATE INDEX idx_itens_fatura_espaco  ON itens_fatura(espaco_id);
CREATE INDEX idx_itens_fatura_cartao  ON itens_fatura(cartao_id);
CREATE INDEX idx_itens_fatura_fatura  ON itens_fatura(fatura_id);
