-- Substitui o enum Banco por um catálogo administrável: tabela global
-- (sem espaco_id — compartilhada por todos os tenants), com logo guardado
-- como bytes no próprio Postgres (sem depender de disco, que é efêmero na
-- hospedagem atual). Só administradores (usuarios.admin) podem gerenciar.

ALTER TABLE usuarios ADD COLUMN admin BOOLEAN NOT NULL DEFAULT false;
UPDATE usuarios SET admin = true WHERE email = 'gabrielfreitas1510@gmail.com';

CREATE TABLE bancos (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome          TEXT NOT NULL,
    cor_primaria  TEXT NOT NULL DEFAULT '#6366f1',
    sigla         TEXT NOT NULL,
    logo          BYTEA,
    logo_tipo     TEXT,
    criado_em     TEXT NOT NULL
);

-- Seed inicial equivalente ao enum anterior — sem logo ainda; o admin sobe
-- as imagens reais depois pela tela de cadastro.
INSERT INTO bancos (nome, cor_primaria, sigla, criado_em) VALUES
    ('Nubank', '#8A05BE', 'nu', '2026-01-01T00:00:00'),
    ('Itaú', '#EC7000', 'itaú', '2026-01-01T00:00:00'),
    ('Bradesco', '#CC092F', 'bradesco', '2026-01-01T00:00:00'),
    ('Santander', '#EC0000', 'santander', '2026-01-01T00:00:00'),
    ('Banco do Brasil', '#FCED00', 'bb', '2026-01-01T00:00:00'),
    ('Caixa Econômica', '#0070AD', 'caixa', '2026-01-01T00:00:00'),
    ('Banco Inter', '#FF7A00', 'inter', '2026-01-01T00:00:00'),
    ('C6 Bank', '#242424', 'c6', '2026-01-01T00:00:00'),
    ('Sicoob', '#00A65E', 'sicoob', '2026-01-01T00:00:00'),
    ('Sicredi', '#7DB61C', 'sicredi', '2026-01-01T00:00:00'),
    ('PicPay', '#21C25E', 'picpay', '2026-01-01T00:00:00'),
    ('Mercado Pago', '#00AEEF', 'mp', '2026-01-01T00:00:00'),
    ('BTG Pactual', '#003087', 'btg', '2026-01-01T00:00:00'),
    ('XP Investimentos', '#1C1C1C', 'xp', '2026-01-01T00:00:00'),
    ('Neon', '#00E599', 'neon', '2026-01-01T00:00:00'),
    ('Banco Pan', '#FF5A00', 'pan', '2026-01-01T00:00:00'),
    ('Safra', '#003057', 'safra', '2026-01-01T00:00:00'),
    ('Banco Original', '#00AA4F', 'original', '2026-01-01T00:00:00'),
    ('Outro', '#6b7280', 'banco', '2026-01-01T00:00:00');

-- contas.banco e cartoes.banco eram TEXT com o nome do enum (V6) — trocam
-- para FK de verdade. Dados antigos em texto não têm correspondência segura
-- com os novos ids (nomes de enum vs. nomes de exibição divergem), então a
-- coluna nova nasce nula e o usuário reseleciona o banco se quiser.
ALTER TABLE contas ADD COLUMN banco_id BIGINT REFERENCES bancos(id);
ALTER TABLE contas DROP COLUMN banco;

ALTER TABLE cartoes ADD COLUMN banco_id BIGINT REFERENCES bancos(id);
ALTER TABLE cartoes DROP COLUMN banco;
