-- Orçamento: limite de gasto por categoria/mês. unique_orcamento_categoria_mes
-- impede duplicidade (dois orçamentos para a mesma categoria no mesmo mês
-- silenciosamente somando limites errados na tela).
CREATE TABLE orcamentos (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoria_id  BIGINT NOT NULL REFERENCES categorias(id),
    mes           TEXT NOT NULL,
    limite        NUMERIC(19,2) NOT NULL,
    espaco_id     BIGINT NOT NULL REFERENCES espacos(id),
    CONSTRAINT unique_orcamento_categoria_mes UNIQUE (espaco_id, categoria_id, mes)
);

CREATE INDEX idx_orcamentos_espaco_mes ON orcamentos(espaco_id, mes);

-- Consultas de orçamento e de resumo por categoria somam transações
-- filtrando por categoria_id — hoje sem índice próprio, vira scan conforme a
-- tabela cresce.
CREATE INDEX idx_transacoes_categoria ON transacoes(categoria_id);
